name = "bos-settings"
description = "System settings app for Bread OS"
binaries = ["bos-settings"]
system_deps = ["webkit2gtk-4.1", "gtk3", "libsoup3", "librsvg", "hicolor-icon-theme"]
optional_system_deps = ["snapper"]
bread_deps = []
license_file = "LICENSE"
desktop_file = "bos-settings.desktop"

[config]
dir = "~/.config"

[install]
post_install = []
